version: "3"

volumes:
  neptune-app-adminer:
  neptune-app-postgres:  
networks:
  umbrella-net:
    name: "umbrella-net"
    external: false
name: neptune-services
services:
  neptune-app:
    image: azguerrero/phoenix-neptune-app
    restart: on-failure
    depends_on: 
      - neptune-app-postgres
    volumes:
      - ../:/neptune-app
    environment:
      PORT: 18323
      PHX_HOST: localhost
      TYRANT_API_BASE_URL: http://tyrant-services-tyrant-api-1:17323
      DATABASE_URL: postgres://postgres:postgres@neptune-app-postgres:5432/neptune_app_dev
      PHX_SERVER: true
    expose:
      - 18323
    ports:
      - 18323:18323 
    networks:
      - umbrella-net
  neptune-app-postgres:
    image: postgres
    volumes:
      - neptune-app-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
    ports:
      - 5432:5432      
    restart: unless-stopped
    networks:
      - umbrella-net
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5432" ]
      interval: 5s
      timeout: 15s
      retries: 1
  neptune-app-adminer:
    image: adminer
    volumes:
      - neptune-app-adminer:/var/lib/postgresql/data
    environment:
      ADMINER_DEFAULT_SERVER: neptune-app-postgres
      ADMINER_DEFAULT_USER: postgres
      ADMINER_DEFAULT_PASSWORD: postgres
      ADMINER_DEFAULT_TYPE: postgresql
    expose:
      - 8080
    ports:
      - 8080:8080      
    restart: unless-stopped
    networks:
      - umbrella-net
